#include <gdt.h>

const gdt32_t ALIGNED(16) __GDT16[3] = {
	GDT32_STATIC(0, 0, 0, 0),
	GDT32_STATIC(
		0xfffff,
		0,
		GDT_ACCESS_READABLE_WRITEABLE | GDT_ACCESS_EXECUTABLE | GDT_ACCESS_NOT_SYSTEM | GDT_ACCESS_PRESENT,
		0
	),
	GDT32_STATIC(
		0xfffff,
		0,
		GDT_ACCESS_READABLE_WRITEABLE | GDT_ACCESS_DIRECTION | GDT_ACCESS_NOT_SYSTEM | GDT_ACCESS_PRESENT,
		0
	)
};