#include <irq/irq.h>

isr_t IRQ_HANDLERS[NUM_IRQS] = { 0 };
irq_info_t IRQ_INFOS[NUM_IRQS] = {
	{ 0, 0,		IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 1, 1,		IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 2, 2,		IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 3, 3,		IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 4, 4,		IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 5, 5,		IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 6, 6,		IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 7, 7,		IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 8, 8,		IRQ_INFO_TRIGGER_MODE_LEVEL,IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 9, 9,		IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 10, 10,	IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 11, 11,	IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 12, 12,	IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 13, 13,	IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 14, 14,	IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH },
	{ 15, 15,	IRQ_INFO_TRIGGER_MODE_EDGE,	IRQ_INFO_POLARITY_ACTIVE_HIGH }
};