#pragma once
#ifndef __STATUS_H
#define __STATUS_H

#include <typedefs.h>

#define STATUS_UNREACHABLE				-19l
#define STATUS_INVALID_PARAMETER_14		-18l
#define STATUS_INVALID_PARAMETER_13		-17l
#define STATUS_INVALID_PARAMETER_12		-16l
#define STATUS_INVALID_PARAMETER_11		-15l
#define STATUS_INVALID_PARAMETER_10		-14l
#define STATUS_INVALID_PARAMETER_9		-13l
#define STATUS_INVALID_PARAMETER_8		-12l
#define STATUS_INVALID_PARAMETER_7		-11l
#define STATUS_INVALID_PARAMETER_6		-10l
#define STATUS_INVALID_PARAMETER_5		-9l
#define STATUS_INVALID_PARAMETER_4		-8l
#define STATUS_INVALID_PARAMETER_3		-7l
#define STATUS_INVALID_PARAMETER_2		-6l
#define STATUS_INVALID_PARAMETER_1		-5l
#define STATUS_INVALID_PARAMETER		-4l
#define STATUS_INVALID_HEADER			-3l
#define STATUS_NOT_FOUND				-2l
#define STATUS_NO_MEMORY				-1l
#define STATUS_OK						0l


typedef long			status_t;

#endif