#pragma once
#ifndef __ACPI_GAS_ADRESS_SPACE_H
#define __ACPI_GAS_ADRESS_SPACE_H

#include <typedefs.h>

#define ACPI_GAS_ADDRESS_SPACE_SYSTEM_MEMORY									0
#define ACPI_GAS_ADDRESS_SPACE_SYSTEM_IO										1
#define ACPI_GAS_ADDRESS_SPACE_PCI_CONFIGURATION_SPACE							2
#define ACPI_GAS_ADDRESS_SPACE_EMBEDDED_CONTROLLER								3
#define ACPI_GAS_ADDRESS_SPACE_SYSTEM_MANAGEMENT_BUS							4
#define ACPI_GAS_ADDRESS_SPACE_SYSTEM_CMOS										5
#define ACPI_GAS_ADDRESS_SPACE_PCI_DEVICE_BAR_TARGET							6
#define ACPI_GAS_ADDRESS_SPACE_INTELLIGENT_PLATFORM_MANAGEMENT_INFRASTRUCTURE	7
#define ACPI_GAS_ADDRESS_SPACE_GENERAL_PURPOSE_IO								8
#define ACPI_GAS_ADDRESS_SPACE_GENERIC_SERIAL_BUS								9
#define ACPI_GAS_ADDRESS_SPACE_PLATFORM_COMMUNICATION_CHANNEL					10

#endif