#include <exception/exception.h>

EXTERN_C void exception_stub0(void);
EXTERN_C void exception_stub1(void);
EXTERN_C void exception_stub2(void);
EXTERN_C void exception_stub3(void);
EXTERN_C void exception_stub4(void);
EXTERN_C void exception_stub5(void);
EXTERN_C void exception_stub6(void);
EXTERN_C void exception_stub7(void);
EXTERN_C void exception_stub8(void);
EXTERN_C void exception_stub9(void);
EXTERN_C void exception_stub10(void);
EXTERN_C void exception_stub11(void);
EXTERN_C void exception_stub12(void);
EXTERN_C void exception_stub13(void);
EXTERN_C void exception_stub14(void);
EXTERN_C void exception_stub15(void);
EXTERN_C void exception_stub16(void);
EXTERN_C void exception_stub17(void);
EXTERN_C void exception_stub18(void);
EXTERN_C void exception_stub19(void);
EXTERN_C void exception_stub20(void);
EXTERN_C void exception_stub21(void);
EXTERN_C void exception_stub22(void);
EXTERN_C void exception_stub23(void);
EXTERN_C void exception_stub24(void);
EXTERN_C void exception_stub25(void);
EXTERN_C void exception_stub26(void);
EXTERN_C void exception_stub27(void);
EXTERN_C void exception_stub28(void);
EXTERN_C void exception_stub29(void);
EXTERN_C void exception_stub30(void);
EXTERN_C void exception_stub31(void);

void exception_init(void* table) {
	idt32_t* idt = (idt32_t*)table;
	init_idt32(&idt[0],		(uintptr_t)exception_stub0,		0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[1],		(uintptr_t)exception_stub1,		0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[2],		(uintptr_t)exception_stub2,		0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[3],		(uintptr_t)exception_stub3,		0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[4],		(uintptr_t)exception_stub4,		0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[5],		(uintptr_t)exception_stub5,		0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[6],		(uintptr_t)exception_stub6,		0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[7],		(uintptr_t)exception_stub7,		0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[8],		(uintptr_t)exception_stub8,		0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[9],		(uintptr_t)exception_stub9,		0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[10],	(uintptr_t)exception_stub10,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[11],	(uintptr_t)exception_stub11,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[12],	(uintptr_t)exception_stub12,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[13],	(uintptr_t)exception_stub13,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[14],	(uintptr_t)exception_stub14,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[15],	(uintptr_t)exception_stub15,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[16],	(uintptr_t)exception_stub16,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[17],	(uintptr_t)exception_stub17,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[18],	(uintptr_t)exception_stub18,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[19],	(uintptr_t)exception_stub19,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[20],	(uintptr_t)exception_stub20,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[21],	(uintptr_t)exception_stub21,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[22],	(uintptr_t)exception_stub22,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[23],	(uintptr_t)exception_stub23,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[24],	(uintptr_t)exception_stub24,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[25],	(uintptr_t)exception_stub25,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[26],	(uintptr_t)exception_stub26,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[27],	(uintptr_t)exception_stub27,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[28],	(uintptr_t)exception_stub28,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[29],	(uintptr_t)exception_stub29,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[30],	(uintptr_t)exception_stub30,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
	init_idt32(&idt[31],	(uintptr_t)exception_stub31,	0x08, IDT_TYPE_INT32, IDT_FLAG_PRESENT);
}